### ISSUE TITLE
Images broken on homepage

### ISSUE THREAD

**Issue by joelstrohmeier** [pixelstrolch/accessible-pdf#47]
The images on your homepage are currently broken. 

See attached screen grab. 
![Accessible-PDF-Accessible-PDF](https://github.com/stebrech/accessible-pdf/assets/20044418/20a6ec0a-046c-470b-8ff5-bdeb44921b19)

**Comment by stebrech** [comment]
Hi @joelstrohmeier
Thanks for opening this issue! Your screenshot shows an older version of the site. Can you delete your browser cache and write if the issue still exists?

**Comment by stebrech** [comment]
Remove service worker https://github.com/stebrech/accessible-pdf/commit/5a9f964da0bfa49031001c141ad7d400cd570db9
