### ISSUE TITLE
Bugfix: a couple of spelling mistakes

### ISSUE THREAD

**Issue by pcraig3** [pixelstrolch/accessible-pdf#48]
Hi there, 

Thanks for providing this resource, it's a good primer for someone looking to quickly pick up the basic concepts. 

I browsed through all the `General tutorials`, and generally found them informative and well written. However, there are a couple of typos that should be easy to fix.

| Issue | Photo | Solution |
|-------|-------|----------|
|  `Acessible` is spelled wrong in the header.  |  <img width="250" alt="Screenshot 2023-10-25 at 1 26 15 PM" src="https://github.com/stebrech/accessible-pdf/assets/2454380/e509fe8d-5764-4a8c-9c9b-6689cc4786a5">     |    Should be `Accessible` (two "c"s)     |
|  On the [PDF Tags](https://accessible-pdf.info/en/basics/general/overview-of-the-pdf-tags/#tabellenelemente) page, `Tabellenelemente` is in German     |    <img width="250" alt="Screenshot 2023-10-25 at 1 27 12 PM" src="https://github.com/stebrech/accessible-pdf/assets/2454380/d12de2a3-be6e-4739-bac3-ca5b2022cbe9">   |    Should say `Table elements`      |

Cheers!

**Comment by stebrech** [comment]
Fixed in https://github.com/stebrech/accessible-pdf/pull/49
